services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-test
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-test123}
      - GF_USERS_ALLOW_SIGN_UP=false
    tmpfs:
      - /var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - test-network

  loki:
    image: grafana/loki:latest
    container_name: loki-test
    tmpfs:
      - /loki
    ports:
      - "3100:3100"
    networks:
      - test-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-test
    tmpfs:
      - /prometheus
    ports:
      - "9090:9090"
    networks:
      - test-network

networks:
  test-network:
    driver: bridge