name: Home Server CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  GRAFANA_PASSWORD: test123
  TZ: America/New_York
  PLEX_CLAIM: ""
  CLOUDFLARE_TUNNEL_TOKEN: "test-token"

jobs:
  validate-setup:
    name: Validate Configuration
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Validate Makefile syntax
      run: |
        echo "🔍 Validating Makefile..."
        make --dry-run help
        echo "✅ Makefile syntax is valid"
        
    - name: Validate Docker Compose syntax
      run: |
        echo "🔍 Validating Docker Compose..."
        docker-compose config > /dev/null
        echo "✅ Docker Compose syntax is valid"
        
    - name: Check script permissions and syntax
      run: |
        echo "🔍 Checking script files..."
        find scripts -name "*.sh" -exec bash -n {} \;
        echo "✅ All scripts have valid syntax"
        
    - name: Test make commands exist
      run: |
        echo "🔍 Testing make commands..."
        make --dry-run setup
        make --dry-run create-env
        make --dry-run start
        make --dry-run stop
        echo "✅ All make commands are valid"

  test-scripts:
    name: Test Scripts
    runs-on: ubuntu-latest
    needs: validate-setup
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Make scripts executable
      run: |
        chmod +x scripts/**/*.sh
        
    - name: Test create-env script
      run: |
        echo "🧪 Testing create-env script..."
        ./scripts/create-env.sh
        
        # Check if .env file was created
        if [ -f ".env" ]; then
          echo "✅ .env file created successfully"
          echo "Contents:"
          cat .env
        else
          echo "❌ .env file was not created"
          exit 1
        fi
        
    - name: Test script syntax
      run: |
        echo "🧪 Testing script syntax..."
        for script in scripts/**/*.sh; do
          echo "Checking $script..."
          bash -n "$script"
          echo "✅ $script syntax is valid"
        done